[package]
name = "linops"
version = "2026.8.1"
edition = "2021"
description = "modular linux system management tui"
license = "AGPL-3.0-only"
repository = "https://github.com/itsnin/linops"

[[bin]]
name = "linops"
path = "src/main.rs"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
tokio = { version = "1", features = ["rt", "macros", "sync", "process", "io-util", "time", "signal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
anyhow = "1"
thiserror = "1"
libc = "0.2"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[profile.dev]
panic = "unwind"
